[package]
name = "splay_tree"
version = "0.2.4"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "Splay Tree based Data Structures (map, set, heap)"
documentation = "http://sile.github.io/rustdocs/splay_tree/splay_tree/"
homepage = "https://github.com/sile/splay_tree"
repository = "https://github.com/sile/splay_tree"
readme = "README.md"
keywords = []
license = "MIT"

[dev-dependencies]
rand = "0.3"
