[package]
name = "splay_tree"
version = "0.2.6"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "Splay Tree based Data Structures (map, set, heap)"
documentation = "https://docs.rs/splay_tree/"
homepage = "https://github.com/sile/splay_tree"
repository = "https://github.com/sile/splay_tree"
readme = "README.md"
keywords = []
license = "MIT"

[dependencies]
serde = { version = "1", optional = true,  default-features = false, features = ["alloc", "derive"] }

[dev-dependencies]
rand = "0.3"

[features]
std = []
default = [ "std" ]
