reorder_imports = true
wrap_comments = true
normalize_comments = true
# reorder_imported_names = true
error_on_line_overflow = false
format_strings = true
struct_field_align_threshold = 30
single_line_if_else_max_width = 80
use_try_shorthand = true
fn_single_line = true
reorder_imports_in_group = true
